name: Build & Release EXE (Windows)

on:
  push:
    tags: ["v*"]      # runs when you push a tag like v1.0.3
  workflow_dispatch: {}  # lets you run it manually

# needed so the workflow can create a Release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --name MemoryTiles --collect-all mediapipe main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MemoryTiles
          path: dist/MemoryTiles.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built exe
        uses: actions/download-artifact@v4
        with:
          name: MemoryTiles
          path: .

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          files: MemoryTiles.exe
          # uncomment to mark as prerelease
          # prerelease: true
